const gameCards = [
  {
    id: 0,
    charName: "Fry",
    charFullName: "Philip J. Fry",
    charImagePath: "./assets/img/cards/00.png",
    charBonus: "none",
    charQuote: "People said I was dumb, but I proved them.",
  },
  {
    id: 1,
    charName: "Bender",
    charFullName: "Bender Bending Rodriguez",
    charImagePath: "./assets/img/cards/01.png",
    charBonus: "none",
    charQuote: "Bite my shiny metal ass!",
  },
  {
    id: 2,
    charName: "Leela",
    charFullName: "Turanga Leela",
    charImagePath: "./assets/img/cards/02.png",
    charBonus: "none",
    charQuote:
      "Well, you obviously won't listen to reason, so I guess I'll listen to idiotic-ness and come with you.",
  },
  {
    id: 3,
    charName: "Zoidberg",
    charFullName: "Doctor John A. Zoidberg",
    charImagePath: "./assets/img/cards/03.png",
    charBonus: "none",
    charQuote: "Woop woop woop",
  },
  {
    id: 4,
    charName: "Farnsworth",
    charFullName: "Professor Hubert J. Farnsworth",
    charImagePath: "./assets/img/cards/04.png",
    charBonus: "none",
    charQuote: "Good news,     everyone!",
  },
  {
    id: 5,
    charName: "Amy",
    charFullName: "Amy Wong",
    charImagePath: "./assets/img/cards/05.png",
    charBonus: "none",
    charQuote: "Ew, pukeatronic!",
  },
  {
    id: 6,
    charName: "Nibbler",
    charFullName: "Lord Nibbler",
    charImagePath: "./assets/img/cards/06.png",
    charBonus: "none",
    charQuote: "Everyone out of the universe, quick!",
  },
  {
    id: 7,
    charName: "Calculon",
    charFullName: "Calculon",
    charImagePath: "./assets/img/cards/07.png",
    charBonus: "none",
    charQuote: "...Add in the carryover from form 16A, then deduct line 2B",
  },
  {
    id: 8,
    charName: "Zapp",
    charFullName: "Zapp Brannigan",
    charImagePath: "./assets/img/cards/08.png",
    charBonus: "none",
    charQuote: "Stop exploding you,  cowards!!",
  },
  {
    id: 9,
    charName: "Kif",
    charFullName: "Kif Kroker",
    charImagePath: "./assets/img/cards/09.png",
    charBonus: "none",
    charQuote: "Dear Diary,I just made love for the second time…",
  },
  {
    id: 10,
    charName: "Hypnotoad",
    charFullName: "Hypnotoad",
    charImagePath: "./assets/img/cards/10.png",
    charBonus: "none",
    charQuote: "All glory to the Hypnotoad!!",
  },
  {
    id: 11,
    charName: "Mom",
    charFullName: "Mom",
    charImagePath: "./assets/img/cards/11.png",
    charBonus: "none",
    charQuote: "Stink pig!",
  },
  {
    id: 12,
    charName: "Hermes",
    charFullName: "Hermes Conrad",
    charImagePath: "./assets/img/cards/12.png",
    charBonus: "none",
    charQuote: "Sweet llamas of the Bahamas!",
  },
  {
    id: 13,
    charName: "Lrrr",
    charFullName: "Lrrr",
    charImagePath: "./assets/img/cards/13.png",
    charBonus: "none",
    charQuote: "My weight is appropriate and attractive.",
  },
  {
    id: 14,
    charName: "Ndnd",
    charFullName: "Ndnd",
    charImagePath: "./assets/img/cards/14.png",
    charBonus: "none",
    charQuote: " Would you like some human with your salt?",
  },
  {
    id: 15,
    charName: "Wernstrom",
    charFullName: "Dr. Ogden Wernstrom",
    charImagePath: "./assets/img/cards/15.png",
    charBonus: "none",
    charQuote: "It's time you left science to the 120-year-olds!",
  },
  {
    id: 16,
    charName: "Robot Devil",
    charFullName: "Robot Devil",
    charImagePath: "./assets/img/cards/16.png",
    charBonus: "none",
    charQuote: "Wow, that was brutal even  by MY standards!",
  },
  {
    id: 17,
    charName: "Cubert",
    charFullName: "Cubert Farnsworth",
    charImagePath: "./assets/img/cards/17.png",
    charBonus: "none",
    charQuote: "That's impossible!",
  },
  {
    id: 18,
    charName: "Richard Nixon's head",
    charFullName: "Richard Nixon's head",
    charImagePath: "./assets/img/cards/18.png",
    charBonus: "none",
    charQuote: "NIXON IS BACK!",
  },
  {
    id: 19,
    charName: "Donbot",
    charFullName: "Donbot",
    charImagePath: "./assets/img/cards/19.png",
    charBonus: "none",
    charQuote: "Their desire 2 keep living shows me no respect.Hey, Blotto, roll down the window and start shooting",
  },
  {
    id: 20,
    charName: "Clamps",
    charFullName: "Francis X. Clampazzo",
    charImagePath: "./assets/img/cards/20.png",
    charBonus: "none",
    charQuote: "I'll give them the clamps!",
  },
  {
    id: 21,
    charName: "Joey Mousepad",
    charFullName: "Joey Mousepad",
    charImagePath: "./assets/img/cards/21.png",
    charBonus: "none",
    charQuote: "Yo!The Mafia supports you. But don't tell no one. Spread the word",
  },
  {
    id: 22,
    charName: "Scruffy",
    charFullName: "Scruffy",
    charImagePath: "./assets/img/cards/22.png",
    charBonus: "none",
    charQuote: "I'm Scruffy..the Janitor",
  },
  {
    id: 23,
    charName: "Terry",
    charFullName: "Terry",
    charImagePath: "./assets/img/cards/23.png",
    charBonus: "none",
    charQuote: "Welcome to the world of tomorrow!",
  },
];

export default gameCards;
